import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../app/globals.css"
import { Provider } from "react-redux";
import Providers from "@/src/components/globalProvider/provider";
import configureStore from "@/src/components/redux/store";
import HomePage from "@/src/components/layout/layoutpage";
const inter = Inter({ subsets: ["latin"] });
const store=configureStore()
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
            <Providers>        
        {children}
        </Providers>
      </body>
    </html>
  );
}
